from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _


class MaximumLengthValidator:
    def __init__(self, max_length=24):
        self.max_length = max_length

    def validate(self, password, user=None):
        if len(password) > self.max_length:
            raise ValidationError(
                self.get_help_text(pronoun="this"),
                code="password_too_long",
                params={"max_length": self.max_length},
            )

    def get_help_text(self, pronoun="your"):
        return _(
            f"{pronoun.capitalize()} password must contain "
            f"no more than {self.max_length} characters"
        )


class SpecialCharacterInclusionValidator:
    DEFAULT_SPECIAL_CHARACTERS = ("$", "%", ":", "#", "!")

    def __init__(self, special_chars=DEFAULT_SPECIAL_CHARACTERS):
        self.special_chars = special_chars

    def validate(self, password, user=None):
        has_specials_chars = False
        for char in self.special_chars:
            if char in password:
                has_specials_chars = True
                break
        if not has_specials_chars:
            raise ValidationError(
                self.get_help_text(pronoun="this"),
                code="password_missing_special_chars",
            )

    def get_help_text(self, pronoun="your"):
        return _(
            f"{pronoun.capitalize()} password must contain at"
            " least one of the following special characters: "
            f"{', '.join(self.special_chars)}"
        )
